### ISSUE TITLE
Bushtrain would you like to work on this???? 

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [LEVIXDDLMAO/Sonic.EXE-2.5-3.0_SC#1]
### What feature do you want to get added on the base engine?

@BushTrain460615

**Comment by MemeHoovy** [comment]
> ### What feature do you want to get added on the base engine?
> @BushTrain460615

I have their discord, I could ask them

**Comment by LEVIXDDLMAO** [comment]
yea please do, i like bushs work!

**Comment by MemeHoovy** [comment]
> yea please do, i like bushs work!

I messaged them

**Comment by LEVIXDDLMAO** [comment]
okay! I think the extra help would be nice ( im so happy he followed me :D )

**Comment by Gothbr4dn** [comment]
I can help

**Comment by LEVIXDDLMAO** [comment]
Yeah! Ill invite you to the repo!

**Comment by MemeHoovy** [comment]
nice

**Comment by LEVIXDDLMAO** [comment]
there!

**Comment by Gothbr4dn** [comment]
thanks

**Comment by LEVIXDDLMAO** [comment]
:D Np!

**Comment by LEVIXDDLMAO** [comment]
can i use your story week png and main menu? from https://github.com/BushTrain460615/Sonic-exe-3.0-source-code

**Comment by LEVIXDDLMAO** [comment]
if thats okay!

**Comment by LEVIXDDLMAO** [comment]
?

**Comment by Gothbr4dn** [comment]
> can i use your story week png and main menu? from https://github.com/BushTrain460615/Sonic-exe-3.0-source-code

sure
